# Generated by Django 4.2 on 2023-11-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employees_images_alter_employees_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='images',
            new_name='profile_pic',
        ),
    ]
